import { Property, Holding, Transaction, Distribution, Valuation } from './types'

export const DEPARTMENTS = [
  'Montevideo', 'Maldonado', 'Canelones', 'Colonia', 'Rocha',
  'Paysandú', 'Salto', 'Rivera', 'Tacuarembó', 'Cerro Largo',
  'Treinta y Tres', 'Lavalleja', 'Durazno', 'Florida', 'Flores',
  'San José', 'Soriano', 'Río Negro', 'Artigas'
]

export const demoProperties: Property[] = [
  {
    id: '1',
    name: 'Apartamento Playa Brava',
    slug: 'apartamento-playa-brava',
    description: 'Moderno apartamento de 2 dormitorios con vista al mar en primera línea de Playa Brava. Edificio con amenities premium: piscina climatizada, gimnasio, parrillero y seguridad 24/7. Ideal para renta turística con alta demanda en temporada.',
    location: 'Punta del Este, Maldonado',
    department: 'Maldonado',
    address: 'Rambla Lorenzo Batlle Pacheco 1234',
    latitude: -34.9477,
    longitude: -54.9367,
    total_value: 420000,
    token_price: 100,
    total_tokens: 4200,
    tokens_sold: 2940,
    annual_yield_pct: 8.5,
    status: 'funding',
    property_type: 'apartment',
    bedrooms: 2,
    bathrooms: 2,
    area_m2: 95,
    images: ['/demo/playa-brava-1.jpg', '/demo/playa-brava-2.jpg'],
    documents: [
      { name: 'Escritura', url: '#', type: 'deed' },
      { name: 'Plano', url: '#', type: 'blueprint' },
    ],
    fideicomiso_number: 'FID-2026-001',
    created_at: '2026-03-15T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  {
    id: '2',
    name: 'Casa en Carrasco',
    slug: 'casa-carrasco',
    description: 'Amplia casa de 4 dormitorios en el corazón de Carrasco, sobre calle arbolada. Jardín de 300m², garaje doble, y piscina. Zona premium de Montevideo con excelente conectividad y servicios. Renta residencial estable todo el año.',
    location: 'Carrasco, Montevideo',
    department: 'Montevideo',
    address: 'Av. Bolivia 2456',
    latitude: -34.8833,
    longitude: -56.0667,
    total_value: 680000,
    token_price: 200,
    total_tokens: 3400,
    tokens_sold: 850,
    annual_yield_pct: 6.2,
    status: 'funding',
    property_type: 'house',
    bedrooms: 4,
    bathrooms: 3,
    area_m2: 280,
    images: ['/demo/carrasco-1.jpg', '/demo/carrasco-2.jpg'],
    documents: [
      { name: 'Escritura', url: '#', type: 'deed' },
    ],
    fideicomiso_number: 'FID-2026-002',
    created_at: '2026-03-20T00:00:00Z',
    updated_at: '2026-04-08T00:00:00Z',
  },
  {
    id: '3',
    name: 'Local Comercial Ciudad Vieja',
    slug: 'local-comercial-ciudad-vieja',
    description: 'Local comercial de 120m² en plena Ciudad Vieja, sobre Peatonal Sarandí. Excelente ubicación con alto tráfico peatonal. Actualmente alquilado a marca reconocida con contrato a 5 años. Rendimiento garantizado por contrato vigente.',
    location: 'Ciudad Vieja, Montevideo',
    department: 'Montevideo',
    address: 'Peatonal Sarandí 678',
    latitude: -34.9058,
    longitude: -56.2044,
    total_value: 350000,
    token_price: 50,
    total_tokens: 7000,
    tokens_sold: 7000,
    annual_yield_pct: 9.8,
    status: 'renting',
    property_type: 'commercial',
    bedrooms: null,
    bathrooms: 1,
    area_m2: 120,
    images: ['/demo/ciudad-vieja-1.jpg'],
    documents: [
      { name: 'Escritura', url: '#', type: 'deed' },
      { name: 'Contrato de alquiler', url: '#', type: 'lease' },
    ],
    fideicomiso_number: 'FID-2026-003',
    created_at: '2026-02-10T00:00:00Z',
    updated_at: '2026-04-01T00:00:00Z',
  },
  {
    id: '4',
    name: 'Terreno Colonia del Sacramento',
    slug: 'terreno-colonia',
    description: 'Terreno de 2.500m² con vista al Río de la Plata en las afueras de Colonia del Sacramento. Zona en pleno desarrollo con nuevo acceso vial. Ideal para proyecto residencial o turístico. Plusvalía proyectada por infraestructura en construcción.',
    location: 'Colonia del Sacramento, Colonia',
    department: 'Colonia',
    address: 'Ruta 1 km 177',
    latitude: -34.4626,
    longitude: -57.8440,
    total_value: 180000,
    token_price: 50,
    total_tokens: 3600,
    tokens_sold: 0,
    annual_yield_pct: 0,
    status: 'coming_soon',
    property_type: 'land',
    bedrooms: null,
    bathrooms: null,
    area_m2: 2500,
    images: ['/demo/colonia-1.jpg'],
    documents: [],
    fideicomiso_number: null,
    created_at: '2026-04-05T00:00:00Z',
    updated_at: '2026-04-05T00:00:00Z',
  },
  {
    id: '5',
    name: 'Penthouse Pocitos',
    slug: 'penthouse-pocitos',
    description: 'Penthouse de 3 dormitorios con terraza panorámica sobre la Rambla de Pocitos. 180m² cubiertos + 60m² de terraza. Vista 360° al mar y la ciudad. Edificio de categoría con amenities completos. Alta demanda de alquiler ejecutivo y turístico.',
    location: 'Pocitos, Montevideo',
    department: 'Montevideo',
    address: 'Rambla República del Perú 1500',
    latitude: -34.9167,
    longitude: -56.1500,
    total_value: 520000,
    token_price: 100,
    total_tokens: 5200,
    tokens_sold: 1560,
    annual_yield_pct: 7.4,
    status: 'funding',
    property_type: 'apartment',
    bedrooms: 3,
    bathrooms: 2,
    area_m2: 180,
    images: ['/demo/pocitos-1.jpg'],
    documents: [
      { name: 'Escritura', url: '#', type: 'deed' },
    ],
    fideicomiso_number: 'FID-2026-005',
    created_at: '2026-04-01T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
  {
    id: '6',
    name: 'Chacra José Ignacio',
    slug: 'chacra-jose-ignacio',
    description: 'Exclusiva chacra de 5 hectáreas en José Ignacio con casa principal y casa de huéspedes. Piscina infinita, huerta orgánica y acceso privado a playa. El destino más exclusivo de Sudamérica con demanda creciente de alquiler premium.',
    location: 'José Ignacio, Maldonado',
    department: 'Maldonado',
    address: 'Camino Arenas de José Ignacio',
    latitude: -34.7833,
    longitude: -54.6333,
    total_value: 1200000,
    token_price: 500,
    total_tokens: 2400,
    tokens_sold: 480,
    annual_yield_pct: 5.8,
    status: 'funding',
    property_type: 'house',
    bedrooms: 6,
    bathrooms: 5,
    area_m2: 450,
    images: ['/demo/jose-ignacio-1.jpg'],
    documents: [
      { name: 'Escritura', url: '#', type: 'deed' },
      { name: 'Plano', url: '#', type: 'blueprint' },
    ],
    fideicomiso_number: 'FID-2026-006',
    created_at: '2026-03-25T00:00:00Z',
    updated_at: '2026-04-10T00:00:00Z',
  },
]

export const demoHoldings: Holding[] = [
  {
    id: 'h1',
    investor_id: 'demo-user',
    property_id: '1',
    tokens: 50,
    purchase_price: 100,
    purchased_at: '2026-03-20T00:00:00Z',
    tx_signature: null,
    status: 'active',
    property: demoProperties[0],
  },
  {
    id: 'h2',
    investor_id: 'demo-user',
    property_id: '3',
    tokens: 200,
    purchase_price: 50,
    purchased_at: '2026-02-15T00:00:00Z',
    tx_signature: null,
    status: 'active',
    property: demoProperties[2],
  },
  {
    id: 'h3',
    investor_id: 'demo-user',
    property_id: '5',
    tokens: 30,
    purchase_price: 100,
    purchased_at: '2026-04-05T00:00:00Z',
    tx_signature: null,
    status: 'active',
    property: demoProperties[4],
  },
]

export const demoTransactions: Transaction[] = [
  {
    id: 't1',
    investor_id: 'demo-user',
    property_id: '1',
    type: 'buy',
    tokens: 50,
    amount: 5000,
    fee: 125,
    tx_signature: null,
    status: 'confirmed',
    created_at: '2026-03-20T10:30:00Z',
    property: demoProperties[0],
  },
  {
    id: 't2',
    investor_id: 'demo-user',
    property_id: '3',
    type: 'buy',
    tokens: 200,
    amount: 10000,
    fee: 250,
    tx_signature: null,
    status: 'confirmed',
    created_at: '2026-02-15T14:00:00Z',
    property: demoProperties[2],
  },
  {
    id: 't3',
    investor_id: 'demo-user',
    property_id: '3',
    type: 'yield',
    tokens: 0,
    amount: 245,
    fee: 0,
    tx_signature: null,
    status: 'confirmed',
    created_at: '2026-04-01T09:00:00Z',
    property: demoProperties[2],
  },
  {
    id: 't4',
    investor_id: 'demo-user',
    property_id: '5',
    type: 'buy',
    tokens: 30,
    amount: 3000,
    fee: 75,
    tx_signature: null,
    status: 'confirmed',
    created_at: '2026-04-05T16:45:00Z',
    property: demoProperties[4],
  },
]

export const demoDistributions: Distribution[] = [
  {
    id: 'd1',
    property_id: '3',
    period: '2026-Q1',
    total_amount: 8575,
    per_token_amount: 1.225,
    distributed_at: '2026-04-01T09:00:00Z',
    status: 'distributed',
  },
]

export const demoValuations: Valuation[] = [
  {
    id: 'v1',
    property_id: '1',
    previous_value: 400000,
    new_value: 420000,
    previous_token_price: 95.24,
    new_token_price: 100,
    change_pct: 5.0,
    appraiser: 'Tasaciones del Este S.A.',
    notes: 'Revaluación semestral. Incremento por mejoras en la zona y demanda turística.',
    valuation_date: '2026-03-01',
    applied_at: '2026-03-05T10:00:00Z',
    status: 'applied',
    created_at: '2026-03-01T09:00:00Z',
    property: demoProperties[0],
  },
  {
    id: 'v2',
    property_id: '3',
    previous_value: 330000,
    new_value: 350000,
    previous_token_price: 47.14,
    new_token_price: 50,
    change_pct: 6.06,
    appraiser: 'Inmobiliaria Nacional Tasaciones',
    notes: 'Revaluación por renovación del contrato de alquiler con incremento de canon.',
    valuation_date: '2026-02-15',
    applied_at: '2026-02-20T14:00:00Z',
    status: 'applied',
    created_at: '2026-02-15T10:00:00Z',
    property: demoProperties[2],
  },
  {
    id: 'v3',
    property_id: '5',
    previous_value: 520000,
    new_value: 545000,
    previous_token_price: 100,
    new_token_price: 104.81,
    change_pct: 4.81,
    appraiser: 'Montevideo Tasaciones Ltda.',
    notes: 'Valuación pendiente de aprobación. Incremento por desarrollo de infraestructura en la zona.',
    valuation_date: '2026-04-10',
    applied_at: null,
    status: 'pending',
    created_at: '2026-04-10T11:00:00Z',
    property: demoProperties[4],
  },
  {
    id: 'v4',
    property_id: '2',
    previous_value: 700000,
    new_value: 680000,
    previous_token_price: 205.88,
    new_token_price: 200,
    change_pct: -2.86,
    appraiser: 'Tasaciones del Este S.A.',
    notes: 'Ajuste de valor por corrección del mercado inmobiliario en la zona.',
    valuation_date: '2026-03-20',
    applied_at: '2026-03-25T09:00:00Z',
    status: 'applied',
    created_at: '2026-03-20T08:00:00Z',
    property: demoProperties[1],
  },
]

export function formatUSD(amount: number): string {
  return new Intl.NumberFormat('es-UY', {
    style: 'currency',
    currency: 'USD',
    minimumFractionDigits: 0,
    maximumFractionDigits: 0,
  }).format(amount)
}

export function formatPercent(value: number): string {
  return `${value.toFixed(1)}%`
}

export function getStatusLabel(status: string): string {
  const labels: Record<string, string> = {
    coming_soon: 'Próximamente',
    funding: 'En financiación',
    funded: 'Financiado',
    renting: 'Generando renta',
    closed: 'Cerrado',
  }
  return labels[status] || status
}

export function getStatusColor(status: string): string {
  const colors: Record<string, string> = {
    coming_soon: 'bg-slate-100 text-slate-600',
    funding: 'bg-blue-50 text-blue-700',
    funded: 'bg-slate-900 text-white',
    renting: 'bg-blue-600 text-white',
    closed: 'bg-slate-100 text-slate-500',
  }
  return colors[status] || 'bg-slate-100 text-slate-600'
}

export function getPropertyTypeLabel(type: string): string {
  const labels: Record<string, string> = {
    apartment: 'Apartamento',
    house: 'Casa',
    land: 'Terreno',
    commercial: 'Comercial',
  }
  return labels[type] || type
}
